name: Python Test with Pytest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3s
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Choose the Python version you want

    - name: Install dependencies
      run: |s
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run pytest
      run: pytest square_test.py
